[logger]
level = "INFO"
path = "/tmp/tmpdir/calendar.log"
[amqp]
uri = "amqp://guest:guest@rabbit:5672/"
exchangeName = "SecondEx"
exchangeType = "direct"
routingKey = "test-key"
body = "foobar"
reliable = true
consumerTag = "simple-consumer"
queue = "test-queue"
timeout = 30