[psql]
dsn = "host=postgres port=5432 user=test password=test dbname=exampledb sslmode=disable"
[amqp]
uri = "amqp://guest:guest@rabbit:5672/"
exchangeName = "SecondEx"
exchangeType = "direct"
routingKey = "test-key"
body = "foobar"
reliable = true
consumerTag = "simple-consumer"
queue = "test-queue"
timeout = 30