version: "3"

networks:
  rabbit:
    driver: bridge
  postgres:
    driver: bridge

services:
  integration_tests:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    restart: on-failure
    expose:
      - 50051
      - 8082
    links:
      - calendar
      - calendar_scheduler
      - calendar_sender
    environment:
      TESTS_AMQP_DSN: "amqp://guest:guest@rabbit:5672/"
    networks:
      - rabbit
      - postgres

  calendar:
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      - rabbit
      - postgres
      - calendar_scheduler
      - calendar_sender
    restart: on-failure
    ports:
      - "50051:50051"
      - "8082:8082"
    expose:
      - 50051
      - 8082
    environment:
      REG_SERVICE_DB_DSN: "postgres://test:test@postgres:5432/exampledb?sslmode=disable"
      REG_SERVICE_AMQP_DSN: "amqp://guest:guest@localhost:5672/"
      REG_SERVICE_SERVER_ADDR: ":8088"
    networks:
      - rabbit
      - postgres

  postgres:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: exampledb
    volumes:
      # https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L145
      - ./migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
    networks:
      - postgres

  calendar_scheduler:
    build:
      context: .
      dockerfile: calendar_scheduler/Dockerfile
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    ports:
      - "8088:8088"
    expose:
      - 8888
    environment:
      NOTIFY_SERVICE_AMQP_DSN: "amqp://guest:guest@localhost:5672/"
    networks:
      - rabbit
      - postgres

  calendar_sender:
    build:
      context: .
      dockerfile: calendar_sender/Dockerfile
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    ports:
      - "8089:8089"
    expose:
      - 8889
    environment:
      NOTIFY_SERVICE_AMQP_DSN: "amqp://guest:guest@localhost:5672/"
    networks:
      - rabbit

  rabbit:
    image: rabbitmq:3.7.17-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 15672
      - 5672
    volumes:
      - ./configs/rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./configs/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbit